spring.application.name=WeatherForecast

spring.datasource.url=jdbc:postgresql://localhost:5432/weather_db
spring.datasource.username=postgres
spring.datasource.password=roberta

spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8085